### ISSUE TITLE
Files missing

### ISSUE THREAD

**Issue by loogabooga** [BAaboe/GoinInvader#1]
# Hi!
I noticed that there are some files missing in this repository

I have attached them below.
[README.md](https://github.com/BAaboe/GoinDefender/files/8050110/README.md)

**Comment by BAaboe** [comment]
# Hi @loogabooga 
I am glad you reached out to me. I will gladly add a readme, if you would be so kind to send me a fitting readme file, that is not some half-life 1 SDK shit, I would be glad to add it.
